# Goal - I have to Lint, Build, Test the code for the project.

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: taskflow_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/taskflow_test
      
    steps: 
      - name: Code Checkout
        uses: actions/checkout@v6

      

      - name: Docker Setup Login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
                
      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/taskflow:latest


  deploy:
    needs: build
    uses: ./.github/workflows/cd.yml
    secrets: inherit     

