
name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Copy .env file
        run: cp .env.example .env

      - name: Docker Setup Login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy containers with Docker Compose
        run: |
          docker compose -p taskflow pull
          docker compose -p taskflow up -d --remove-orphans
          docker exec taskflow flask db upgrade