# Goal - To Run End to End DecSecOps pipeline 

name: DevSecOps

on:
    push:

jobs:
    
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml
